### ISSUE TITLE
Exercise 1 : Add various shapes instead of blocks

### ISSUE THREAD

**Issue by yvsssantosh** [pandilladivya/react-training#1]
#### Exercise 1 : Add various shapes instead of blocks

* Currently we have only blocks defining all various colours. We need to make it in such a way that various kinds of shapes are shown in the colour sent through props

**Comment by yvsssantosh** [comment]
@pandilladivya 
Let me know if I can put a PR on this issue

**Comment by pandilladivya** [comment]
Yes
